networks:
  backend:

services:
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      EXTERNAL_URL: 127-0-0-1.sslip.io
      TLS_MODE: internal  # off: httpのみ internal: 自己署名証明書 <your_email>: Let's Encrypt
    volumes:
      - ./overlays/caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - backend

  authelia:
    image: authelia/authelia
    # ports:
    #   - "9091:9091"
    volumes:
      - ./.volumes/authelia/configuration.yml:/config/configuration.yml:ro
      - ./.volumes/authelia/users_database.yml:/config/users_database.yml:ro
    networks:
      - backend

  cron:
    container_name: cron
    build: .
    restart: unless-stopped    
    # ports:
    #   - "9001:9001"  # supervisor用ポート（ただし、ログなど標準出力に出力しているので、ログなどは確認できず、プロセス確認ぐらいしか約に立たない）
    #   - "8000:8000"  # http server
    #   - "8100:8100"  # WebDav
    volumes:
      - ./.volumes/webdav:/webdav
    networks:
      - backend

  httpbin:
    image: kennethreitz/httpbin
    networks:
      - backend
    # ports:
      # - "9112:80"
  