---
###############################################################
#                   Authelia configuration                    #
###############################################################
theme: "dark"
server:
  address: 'tcp://:9091'
#   tls:
#     disable: true
log:
  level: 'debug'
identity_validation:
  reset_password:
    jwt_secret: 'a_very_important_secret'
authentication_backend:
  file:
    path: '/config/users_database.yml'
storage:
  encryption_key: 'you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this'
  local:
    path: '/config/db.sqlite3'
access_control:
  default_policy: 'deny'
  rules:
    - domain: 'traefix.example.com'
      policy: 'bypass'
    # - domain: 'auth.example.com'
    #   policy: 'one_factor'
    - domain: '127-0-0-1.sslip.io'
      policy: 'one_factor'
session:
  name: authelia_session
  secret: 'insecure_session_secret'
  cookies:
    - name: 'authelia_session'
      domain: '127-0-0-1.sslip.io'  # Should match whatever your root protected domain is
      authelia_url: 'https://auth.127-0-0-1.sslip.io'
      expiration: '1 hour'  # 1 hour
      inactivity: '5 minutes'  # 5 minutes
      default_redirection_url: 'https://webdav.127-0-0-1.sslip.io'  # ログイン後遷移先
regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'
notifier:
  filesystem:
    filename: /config/notification.txt
  # smtp:
  #   address: 'smtp://smtp.gmail.com:587'
  #   timeout: '5s'
  #   username: 'google_account_name'
  #   password: 'application_password'
  #   sender: "Authelia <admin@example.com>"
  #   identifier: 'localhost'
  #   subject: "[Authelia] {title}"
